apiVersion: v1
kind: Pod
metadata:
 name: mysqlpod
spec: 
 containers:
  - name: mysqlpod
    image: mysql:8.0
    ports:
     - containerPort: 3306
    env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: root
        - name: "MYSQL_DATABASE"
          value: exercicio
        - name: "MYSQL_PASSWORD"
          value: root